services:
  cryptowave-server:
    container_name: cryptowave-server
    networks:
      - cryptowave-network
    build:
      context: .
    environment:
      DB_NAME: $DB_NAME
      DB_URL: $DB_URL
      PORT: $PORT
      ADMIN: $ADMIN
      JWT_ACCESS_SECRET: $JWT_ACCESS_SECRET
      JWT_REFRESH_SECRET: $JWT_REFRESH_SECRET
      SMTP_HOST: $SMTP_HOST
      SMTP_PORT: $SMTP_PORT
      SMTP_USER: $SMTP_USER
      SMTP_PASSWORD: $SMTP_PASSWORD
      CLIENT_URL: $CLIENT_URL
      EXTERNAL_NEWSAPI_KEY: $EXTERNAL_NEWSAPI_KEY
      EXTERNAL_EXCHANGES_APIKEY: $EXTERNAL_EXCHANGES_APIKEY
      EXTERNAL_COINDESK_APIKEY: $EXTERNAL_COINDESK_APIKEY
      BOT_TOKEN: $BOT_TOKEN
    ports:
      - 5002:5000
    depends_on:
      - cryptowave-mongodb
    restart: unless-stopped

  cryptowave-mongodb:
    image: mongo:latest
    container_name: cryptowave-mongodb
    ports:
      - "27019:27017"
    volumes:
      - cryptowave-mongodb-data:/data/db
    networks:
      - cryptowave-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    restart: unless-stopped

volumes:
  cryptowave-mongodb-data:
  
networks:
  cryptowave-network:
